export const tituloCard = "text-2xl md:text-3xl font-bold text-cyan-600 pb-3 text-center"
export const headerTable = "text-2xl md:text-3xl font-bold text-cyan-600 pb-3 text-center"
export const headerCarousel = "w-full py-3 outline-none bg-transparent text-lg text-center text-cyan-800 font-bold"
export const grayContent = "grid grid-cols-2 w-full bg-slate-300"
export const sideValue = "col-auto px-2 py-3 bg-transparent text-cyan-800 text-lg"
export const whiteContent = "grid grid-cols-2 w-full bg-white"
export const colTransparent = "col-auto bg-transparent"
export const inputTransparentBold = "w-full py-3 outline-none bg-transparent text-center text-cyan-800 font-bold"
export const inputTransparent = "w-full py-3 outline-none bg-transparent text-center text-cyan-800 flex justify-center items-center"
export const threeColumnsHeader = 'grid grid-cols-3 text-lg font-bold p-3 border-t border-b border-t-1 border-b-1 border-cyan-800'
export const fourColumnsHeader = 'grid grid-cols-4 text-lg font-bold p-3 border-t border-b border-t-1 border-b-1 border-cyan-800'
export const columnHeader = "row py-3 text-lg text-cyan-800 font-bold text-center"
export const threeColumnsGrayContent = 'grid grid-cols-3 bg-slate-300'
export const fourColumnsGrayContent = 'grid grid-cols-4 bg-slate-300'
export const fourWhiteColumnsContent = 'grid grid-cols-4 bg-white'
export const tableSideValue = 'row py-3 text-lg text-cyan-800'
export const rowTextCenter = 'row text-center'
export const threeColumnsWhiteContent = 'grid grid-cols-3 bg-white'
export const twocColumnsWhiteContent = 'border-b border-b-1 border-cyan-800 grid grid-cols-2 w-full bg-white'
export const componentTitle = "w-full text-center text-cyan-600 font-bold text-2xl md:text-3xl p-3"
